# Load Neccessay Libraries 

In [1]:
import numpy as np

# List Comprehension

In [2]:
# create a list names with some names
names = ['Asiya', 'Shahnaz', 'Ibrahim','John', 'Jerry', 'Khan', 'Kramer', 'Ebrahim', 'Elaine', 'George', 'Newman']

# Print the list created by using list comprehension
best_list = [name for name in names if len(name) >= 6]
print(best_list)

['Shahnaz', 'Ibrahim', 'Kramer', 'Ebrahim', 'Elaine', 'George', 'Newman']


# Zen of Python

In [3]:
# Zen of Python
import this 

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


# Range and Lists

In [4]:
# Create a range object that goes from 0 to 100
nums = range(101)
print(type(nums))

# Convert nums to a list
nums_list = list(nums)
print(nums_list)

# Create a new list of odd numbers from 1 to 111 by unpacking a range object
nums_list2 = [*range(1,112,2)]
print(nums_list2)

<class 'range'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99, 101, 103, 105, 107, 109, 111]


# Python's Built-in Function Enumerate

### Python's built-in enumerate() function allows to create an index for each item in the object you give it. We can use list comprehension, or even unpack the enumerate object directly into a list, to write a nice simple one-liner. Lets see this in action.

In [5]:
# for loop to use enumerate
indexed_names = []
for i, name in enumerate(names):
    index_name = (i,name)
    indexed_names.append(index_name) 
print(indexed_names)

# Rewrite the above for loop using list comprehension
indexed_names_comp = [(i, name) for i,name in enumerate(names)]
print(indexed_names_comp)

# Unpack an enumerate object with a starting index of one
indexed_names_unpack = [* enumerate(names, 1)]
print(indexed_names_unpack)

[(0, 'Asiya'), (1, 'Shahnaz'), (2, 'Ibrahim'), (3, 'John'), (4, 'Jerry'), (5, 'Khan'), (6, 'Kramer'), (7, 'Ebrahim'), (8, 'Elaine'), (9, 'George'), (10, 'Newman')]
[(0, 'Asiya'), (1, 'Shahnaz'), (2, 'Ibrahim'), (3, 'John'), (4, 'Jerry'), (5, 'Khan'), (6, 'Kramer'), (7, 'Ebrahim'), (8, 'Elaine'), (9, 'George'), (10, 'Newman')]
[(1, 'Asiya'), (2, 'Shahnaz'), (3, 'Ibrahim'), (4, 'John'), (5, 'Jerry'), (6, 'Khan'), (7, 'Kramer'), (8, 'Ebrahim'), (9, 'Elaine'), (10, 'George'), (11, 'Newman')]


# Python's Built-in map() Function

In [6]:
# Use map to apply str.upper function to each element in names
names_map  = map(str.upper, names)

# Print the type of the names_map
print(type(names_map))

# Unpack names_map into a list
names_uppercase = [* names_map]

# Print the list created above
print(names_uppercase) 

<class 'map'>
['ASIYA', 'SHAHNAZ', 'IBRAHIM', 'JOHN', 'JERRY', 'KHAN', 'KRAMER', 'EBRAHIM', 'ELAINE', 'GEORGE', 'NEWMAN']


# Numpy Arrays

In [7]:
# create a numpy array nums
nums = np.array([[ 1,  2,  3,  4,  5], [ 6,  7,  8,  9, 10]])

In [8]:
# Display elements of nums
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
# Get data type of nums
nums.dtype

dtype('int64')

In [10]:
# create a numpy array numbers
numbers = np.array([[ 1,  2.5,  3,  4,  5], [ 6,  7,  8,  9.5, 10]])

In [11]:
# Display elements of numbers
numbers

array([[ 1. ,  2.5,  3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ,  9.5, 10. ]])

In [12]:
# Get data type of numbers
numbers.dtype

dtype('float64')

# NumPy's Array Broadcasting and Vectorize Operations

### Python lists don't support broadcasting. Using numpy arrays allows us to take advantage of an array's memory efficient nature and easily perform mathematical operations on our data.

In [13]:
# Print second row of nums
print(nums[0,1])

2


In [14]:
# Print all elements of nums that are greater than six
print(nums[nums > 6])

[ 7  8  9 10]


In [15]:
# Double every element of nums
nums_dbl = nums * 2
print(nums_dbl)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [16]:
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
# Replace the third column of nums
nums[:,2] = nums[:, 2] + 1
print(nums)

[[ 1  2  4  4  5]
 [ 6  7  9  9 10]]


# Task To Apply Everything

In [22]:
def welcome_guest(guest_and_time):
  guest = guest_and_time[0]
  arrival_time = guest_and_time[1]
  welcome_string = "Welcome to Festivus {}... You\'re {} min late.".format(guest,arrival_time)
  return welcome_string

In [23]:
# Create a list of arrival times
arrival_times = [*range(10,90,10)]

# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[i],time) for i,time in enumerate(new_times)]

# Map the welcome_guest function to each (guest,time) pair
welcome_map = map(welcome_guest, guest_arrivals)

guest_welcomes = [*welcome_map]
print(*guest_welcomes, sep='\n')

Welcome to Festivus Asiya... You're 7 min late.
Welcome to Festivus Shahnaz... You're 17 min late.
Welcome to Festivus Ibrahim... You're 27 min late.
Welcome to Festivus John... You're 37 min late.
Welcome to Festivus Jerry... You're 47 min late.
Welcome to Festivus Khan... You're 57 min late.
Welcome to Festivus Kramer... You're 67 min late.
Welcome to Festivus Ebrahim... You're 77 min late.
